clear;clc; close all;
y1=resizedImageBW('./rostros/1mujer.jpg');
y2=resizedImageBW('./rostros/2hombre.jpg');
y3=resizedImageBW('./rostros/3hombre.jpg');
y4=resizedImageBW('./rostros/4hombre.jpg');
y5=resizedImageBW('./rostros/5mujer.jpg');
y6=resizedImageBW('./rostros/6mujer.jpg');
y7=resizedImageBW('./rostros/7mujer.jpg');
y8=resizedImageBW('./rostros/8hombre.jpg');
y9=resizedImageBW('./rostros/9hombre.jpg');
y10=resizedImageBW('./rostros/10mujer.png');
y11=resizedImageBW('./rostros/11hombre.jpg');
y12=resizedImageBW('./rostros/12mujer.jpg');
y13=resizedImageBW('./rostros/13mujer.jpg');
y14=resizedImageBW('./rostros/14hombre.jpg');
y15=resizedImageBW('./rostros/15hombre.jpg');
y16=resizedImageBW('./rostros/16mujer.jpg');
y17=resizedImageBW('./rostros/17mujer.jpg');
y18=resizedImageBW('./rostros/18hombre.jpg');
y19=resizedImageBW('./rostros/19mujer.jpg');
y20=resizedImageBW('./rostros/20mujer.jpg');
y21=resizedImageBW('./rostros/21hombre.jpg');
y22=resizedImageBW('./rostros/22hombre.jpg');
y23=resizedImageBW('./rostros/23mujer.jpg');
y24=resizedImageBW('./rostros/24mujer.jpg');
y25=resizedImageBW('./rostros/25hombre.jpg');
y26=resizedImageBW('./rostros/26hombre.jpg');
y27=resizedImageBW('./rostros/27mujer.jpg');
y28=resizedImageBW('./rostros/28hombre.jpg');


